// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/conocenos/congregacion.tsx";
import * as $2 from "./routes/conocenos/hna-juana.tsx";
import * as $3 from "./routes/conocenos/index.tsx";
import * as $4 from "./routes/contacto/index.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/sedes/index.tsx";
import * as $7 from "./routes/sedes/los-olivos.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/conocenos/congregacion.tsx": $1,
    "./routes/conocenos/hna-juana.tsx": $2,
    "./routes/conocenos/index.tsx": $3,
    "./routes/contacto/index.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/sedes/index.tsx": $6,
    "./routes/sedes/los-olivos.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
